### PR TITLE
Update plugins.json for "AirParty/siyuan-plugin-niop-DataBaseTable",

### PR DESCRIPTION
**Pull request by AirParty**
制卡制表的插件
card/table  gen

If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

### CODE REVIEW

**Comment by 88250** [comment]
image

Thank you.

**Comment by AirParty** [comment]
already updata url ，republic package

**Comment by 88250** [comment]
Please upgrade the version num and launch a new release.

**Comment by AirParty** [comment]
V0.8.0->V0.8.1

**Pull request merged**
