### PR TITLE
添加新插件 add-shortcut-to-topbar

### PR DESCRIPTION
**Pull request by iamqiz**
If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

### CODE REVIEW

**Comment by 88250** [comment]
请完成 Release 步骤。

**Comment by iamqiz** [comment]
@88250  ok

**Comment by 88250** [comment]
我这里看还是没有 Release：

image

**Comment by iamqiz** [comment]
@88250 原来是那个   OK了

**Comment by 88250** [comment]
感谢贡献！

**Pull request merged**
