### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by pakeh2866**
If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

### CODE REVIEW

**Comment by 88250** [comment]
请按开发说明打包并创建 Release

**Comment by pakeh2866** [comment]
> 请按开发说明打包并创建 Release

刚打包完了

**Comment by 88250** [comment]
Release 里面没有上传 package.zip

**Comment by pakeh2866** [comment]
理论上应该行了

**Comment by pakeh2866** [comment]
> ## Pull Request Check Report
> ### Add `0` Icon Repo
> ### Add `1` Plugin Repo
> #### [pakeh2866/siyuan-css-img-width](https://github.com/pakeh2866/siyuan-css-img-width)
> * [x]  Release that must exist
>   
>   * [x]  [Current Latest Release](https://github.com/pakeh2866/siyuan-css-img-width/releases/tag/siyuan)
>   * [ ]  `package.zip`
> * [x]  Files that must exist
>   
>   * [x]  [plugin.json](https://github.com/pakeh2866/siyuan-css-img-width/blob/073e76b2e6d65ab9755c0beaa2000109afd5c5f4/plugin.json)
>   * [x]  [icon.png](https://github.com/pakeh2866/siyuan-css-img-width/blob/073e76b2e6d65ab9755c0beaa2000109afd5c5f4/icon.png)
>   * [x]  [preview.png](https://github.com/pakeh2866/siyuan-css-img-width/blob/073e76b2e6d65ab9755c0beaa2000109afd5c5f4/preview.png)
>   * [x]  [README.md](https://github.com/pakeh2866/siyuan-css-img-width/blob/073e76b2e6d65ab9755c0beaa2000109afd5c5f4/README.md)
> * [x]  Attributes that must exist in `plugin.json`
>   
>   * [x]  `name`: `siyuan-css-img-width`
>     
>     * [x]  Is a valid name
>     * [x]  Not conflict with other plugin name
>   * [x]  `version`: `0.1.0`
>   * [x]  `author`: `pakeh`
>   * [x]  `url`: https://github.com/pakeh2866
> 
> ### Add `0` Template Repo
> ### Add `0` Theme Repo
> ### Add `0` Widget Repo

test

**Comment by 88250** [comment]
嗯，可以了，感谢贡献。

**Pull request merged**
