### PR TITLE
add_siyuan_leave_to_lock

### PR DESCRIPTION
**Pull request by zxkmm**
If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

另外请问 @Vanessa219 方不方便插件前端API加个锁屏API？这样我就不需要用这种不优雅的方法实现了。

### CODE REVIEW

**Comment by zxkmm** [comment]
类名忘记改了，先设为draft

**Comment by zxkmm** [comment]
https://github.com/zxkmm/siyuan_leave_to_lock/commit/3ddeec15856a40df7819b222784974f3c0134925

**Comment by Vanessa219** [comment]
https://github.com/siyuan-note/siyuan/issues/10006 添加了，但是锁屏后会刷新页面，你看一下是否可以使用？

**Comment by zxkmm** [comment]
谢谢老大！那我去研究下怎么编译思源

**Pull request merged**
