### PR TITLE
Update themes.json

### PR DESCRIPTION
**Pull request by pureTrue**
If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

### CODE REVIEW

**Comment by pureTrue** [comment]
怪了，已经检查过theme.json了，这些属性都有啊

**Comment by 88250** [comment]
Action 日志：

```
W 2024/12/30 02:34:36 main.go:261: check repo <puretrue/siyuan-theme-darkside> manifest file <https://raw.githubusercontent.com/puretrue/siyuan-theme-darkside/0c430df2b272669926a2fd8848509d590674c884/theme.json> failed: invalid character '"' after object key:value pair
```

**Comment by pureTrue** [comment]
好了，我需要重新拉取请求吗？ @88250

**Comment by 88250** [comment]
不需要，close / reopen 就会重新检查

**Comment by 88250** [comment]
还是有问题哦，release 的 package.zip 里没有改：

```
W 2024/12/30 07:57:40 main.go:261: check repo <puretrue/siyuan-theme-darkside> manifest file <https://raw.githubusercontent.com/puretrue/siyuan-theme-darkside/aa626aa1e94d2876be1c687378436c533fcc35b0/theme.json> failed: invalid character '"' after object key:value pair
```

**Comment by 88250** [comment]
name 还是有问题：

```
W 2024/12/30 08:33:07 main.go:283: repo <puretrue/siyuan-theme-darkside> name <DarkSide> is not equal to repo name <siyuan-theme-darkside>
```

**Comment by 88250** [comment]
感谢你的贡献，思源有你更精彩！
Thank you for your contribution. SiYuan will be more wonderful with you!

**Pull request merged**
