### PR TITLE
Update themes.json

### PR DESCRIPTION
**Pull request by QYLexpired**
If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

### CODE REVIEW

**Comment by 88250** [comment]
感谢你的贡献，思源有你更精彩！
Thank you for your contribution. SiYuan will be more wonderful with you!

**Comment by QYLexpired** [comment]
屏幕截图 2024-12-24 231908
为什么我这里不显示name，是有什么错误吗

**Comment by 88250** [comment]
我手动检查了下 theme.json 应该没有问题，暂时忽略这个检查项。

**Comment by 88250** [comment]
image

可能是 release 里的 package.zip 有问题，麻烦检查一下。

**Pull request merged**
