### PR TITLE
Update widgets.json

### PR DESCRIPTION
**Pull request by ScottXjw**
Add a pendant path in widgets.json

If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

### CODE REVIEW

**Comment by 88250** [comment]
Please check the followings:

image

image

**Comment by 88250** [comment]
Please check your widget.json:

image

**Comment by ScottXjw** [comment]
Modified

**Review by ScottXjw — COMMENTED** [review]
y

**Comment by 88250** [comment]
你好，package.zip 也需要重新打包并发布新版本（版本号需要变化）。

**Comment by 88250** [comment]
另外，这部分请确认无误后手动勾选：

image

**Comment by 88250** [comment]
目前构建还是报错，请检查 https://github.com/siyuan-note/bazaar/actions/runs/7095461729/job/19312414155

image

**Pull request merged**
