### PR TITLE
Update plugins.json for "siyuan-plugin-fold-button

### PR DESCRIPTION
**Pull request by AirParty**
add new plugin siyuan-plugin-fold-button

If you are submitting a new bazaar package for the first time, please confirm the following information.

* [x] The repository is public
* [x] Include the appropriate open source license file `LICENSE`
* [x] Does not involve infringing content, such as non-commercial font files

### CODE REVIEW

**Comment by 88250** [comment]
image

**Comment by AirParty** [comment]
已经添加 url

**Comment by AirParty** [comment]
v0.1->v0.1.1，重新release包

**Comment by 88250** [comment]
合并了，感谢你为思源发展做出贡献。

**Pull request merged**
